info:
    description:
        "Registration REST API. A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.amf.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "RegistrationRest"
    version: v1.0
    openapi: 3.0.1

paths:
    /registration:

        post:
            description: Creates a new account
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AccountInfo'
                    application/xml:
                        schema:
                            $ref: '#/components/schemas/AccountInfo'

            responses:
                201:
                    description: Successfully created a new account

            tags: ["AccountInfo"]

components:
    schemas:
        AccountInfo:
            description: Model containing account info
            type: object
            properties:
                firstName:
                    type: string
                    example: John

                lastName:
                    type: string
                    example: Doe

                emailAddress:
                    type: string
                    example: johndoe@gmail.com

                userName:
                    type: string
                    example: johnDoe

                male:
                    type: boolean
                    example: true

                birthday:
                    type: string
                    example: 1998-12-30

                password:
                    type: string
                    example: Pass123#

                homePhone:
                    type: string
                    example: 1234567890

                mobilePhone:
                    type: string
                    example: 0987654321

                address1:
                    type: string
                    example: main street

                address2:
                    type: string
                    example: other street

                city:
                    type: string
                    example: big city

                state:
                    type: string
                    example: alaska

                zipCode:
                    type: string
                    example: 54321

                securityQuestion:
                    type: integer
                    example: 0

                securityAnswer:
                    type: string
                    example: my answer

                acceptedTerms:
                    type: boolean
                    example: true